<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="..\AeC.Domain\AeC.Domain.csproj"/><ProjectReference Include="..\AeC.Shared\AeC.Shared.csproj"/></ItemGroup></Project>
