CREATE TABLE Usuarios (Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY, Nome NVARCHAR(150) NOT NULL, Usuario NVARCHAR(100) NOT NULL, Senha NVARCHAR(255) NOT NULL);
CREATE UNIQUE INDEX IX_Usuarios_Usuario ON Usuarios(Usuario);
CREATE TABLE Enderecos (Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY, CEP NVARCHAR(9) NOT NULL, Logradouro NVARCHAR(200) NOT NULL, Complemento NVARCHAR(200) NULL, Bairro NVARCHAR(120) NOT NULL, Cidade NVARCHAR(120) NOT NULL, UF CHAR(2) NOT NULL, Numero NVARCHAR(20) NOT NULL, UsuarioId INT NOT NULL, CONSTRAINT FK_Enderecos_Usuarios_UsuarioId FOREIGN KEY (UsuarioId) REFERENCES Usuarios(Id) ON DELETE CASCADE);
CREATE INDEX IX_Enderecos_UsuarioId ON Enderecos(UsuarioId); CREATE INDEX IX_Enderecos_CEP ON Enderecos(CEP); CREATE INDEX IX_Enderecos_Cidade ON Enderecos(Cidade);
